services:

  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: hqmania
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - hqmania-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8000:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - hqmania-network

networks:
  hqmania-network:
    driver: bridge